/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spond.data.web.metno.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ForecastTimeInstant
 */
public class ForecastTimeInstantTest {
    private final ForecastTimeInstant model = new ForecastTimeInstant();

    /**
     * Model tests for ForecastTimeInstant
     */
    @Test
    public void testForecastTimeInstant() {
        // TODO: test ForecastTimeInstant
    }

    /**
     * Test the property 'airPressureAtSeaLevel'
     */
    @Test
    public void airPressureAtSeaLevelTest() {
        // TODO: test airPressureAtSeaLevel
    }

    /**
     * Test the property 'airTemperature'
     */
    @Test
    public void airTemperatureTest() {
        // TODO: test airTemperature
    }

    /**
     * Test the property 'cloudAreaFraction'
     */
    @Test
    public void cloudAreaFractionTest() {
        // TODO: test cloudAreaFraction
    }

    /**
     * Test the property 'cloudAreaFractionHigh'
     */
    @Test
    public void cloudAreaFractionHighTest() {
        // TODO: test cloudAreaFractionHigh
    }

    /**
     * Test the property 'cloudAreaFractionLow'
     */
    @Test
    public void cloudAreaFractionLowTest() {
        // TODO: test cloudAreaFractionLow
    }

    /**
     * Test the property 'cloudAreaFractionMedium'
     */
    @Test
    public void cloudAreaFractionMediumTest() {
        // TODO: test cloudAreaFractionMedium
    }

    /**
     * Test the property 'dewPointTemperature'
     */
    @Test
    public void dewPointTemperatureTest() {
        // TODO: test dewPointTemperature
    }

    /**
     * Test the property 'fogAreaFraction'
     */
    @Test
    public void fogAreaFractionTest() {
        // TODO: test fogAreaFraction
    }

    /**
     * Test the property 'relativeHumidity'
     */
    @Test
    public void relativeHumidityTest() {
        // TODO: test relativeHumidity
    }

    /**
     * Test the property 'windFromDirection'
     */
    @Test
    public void windFromDirectionTest() {
        // TODO: test windFromDirection
    }

    /**
     * Test the property 'windSpeed'
     */
    @Test
    public void windSpeedTest() {
        // TODO: test windSpeed
    }

    /**
     * Test the property 'windSpeedOfGust'
     */
    @Test
    public void windSpeedOfGustTest() {
        // TODO: test windSpeedOfGust
    }

}
