/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spond.data.web.metno.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ForecastTimeStepDataInstant
 */
public class ForecastTimeStepDataInstantTest {
    private final ForecastTimeStepDataInstant model = new ForecastTimeStepDataInstant();

    /**
     * Model tests for ForecastTimeStepDataInstant
     */
    @Test
    public void testForecastTimeStepDataInstant() {
        // TODO: test ForecastTimeStepDataInstant
    }

    /**
     * Test the property 'details'
     */
    @Test
    public void detailsTest() {
        // TODO: test details
    }

}
