/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spond.data.web.metno.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ForecastTimePeriod
 */
public class ForecastTimePeriodTest {
    private final ForecastTimePeriod model = new ForecastTimePeriod();

    /**
     * Model tests for ForecastTimePeriod
     */
    @Test
    public void testForecastTimePeriod() {
        // TODO: test ForecastTimePeriod
    }

    /**
     * Test the property 'airTemperatureMax'
     */
    @Test
    public void airTemperatureMaxTest() {
        // TODO: test airTemperatureMax
    }

    /**
     * Test the property 'airTemperatureMin'
     */
    @Test
    public void airTemperatureMinTest() {
        // TODO: test airTemperatureMin
    }

    /**
     * Test the property 'precipitationAmount'
     */
    @Test
    public void precipitationAmountTest() {
        // TODO: test precipitationAmount
    }

    /**
     * Test the property 'precipitationAmountMax'
     */
    @Test
    public void precipitationAmountMaxTest() {
        // TODO: test precipitationAmountMax
    }

    /**
     * Test the property 'precipitationAmountMin'
     */
    @Test
    public void precipitationAmountMinTest() {
        // TODO: test precipitationAmountMin
    }

    /**
     * Test the property 'probabilityOfPrecipitation'
     */
    @Test
    public void probabilityOfPrecipitationTest() {
        // TODO: test probabilityOfPrecipitation
    }

    /**
     * Test the property 'probabilityOfThunder'
     */
    @Test
    public void probabilityOfThunderTest() {
        // TODO: test probabilityOfThunder
    }

    /**
     * Test the property 'ultravioletIndexClearSkyMax'
     */
    @Test
    public void ultravioletIndexClearSkyMaxTest() {
        // TODO: test ultravioletIndexClearSkyMax
    }

}
