/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spond.data.web.metno.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ForecastUnits
 */
public class ForecastUnitsTest {
    private final ForecastUnits model = new ForecastUnits();

    /**
     * Model tests for ForecastUnits
     */
    @Test
    public void testForecastUnits() {
        // TODO: test ForecastUnits
    }

    /**
     * Test the property 'airPressureAtSeaLevel'
     */
    @Test
    public void airPressureAtSeaLevelTest() {
        // TODO: test airPressureAtSeaLevel
    }

    /**
     * Test the property 'airTemperature'
     */
    @Test
    public void airTemperatureTest() {
        // TODO: test airTemperature
    }

    /**
     * Test the property 'airTemperatureMax'
     */
    @Test
    public void airTemperatureMaxTest() {
        // TODO: test airTemperatureMax
    }

    /**
     * Test the property 'airTemperatureMin'
     */
    @Test
    public void airTemperatureMinTest() {
        // TODO: test airTemperatureMin
    }

    /**
     * Test the property 'cloudAreaFraction'
     */
    @Test
    public void cloudAreaFractionTest() {
        // TODO: test cloudAreaFraction
    }

    /**
     * Test the property 'cloudAreaFractionHigh'
     */
    @Test
    public void cloudAreaFractionHighTest() {
        // TODO: test cloudAreaFractionHigh
    }

    /**
     * Test the property 'cloudAreaFractionLow'
     */
    @Test
    public void cloudAreaFractionLowTest() {
        // TODO: test cloudAreaFractionLow
    }

    /**
     * Test the property 'cloudAreaFractionMedium'
     */
    @Test
    public void cloudAreaFractionMediumTest() {
        // TODO: test cloudAreaFractionMedium
    }

    /**
     * Test the property 'dewPointTemperature'
     */
    @Test
    public void dewPointTemperatureTest() {
        // TODO: test dewPointTemperature
    }

    /**
     * Test the property 'fogAreaFraction'
     */
    @Test
    public void fogAreaFractionTest() {
        // TODO: test fogAreaFraction
    }

    /**
     * Test the property 'precipitationAmount'
     */
    @Test
    public void precipitationAmountTest() {
        // TODO: test precipitationAmount
    }

    /**
     * Test the property 'precipitationAmountMax'
     */
    @Test
    public void precipitationAmountMaxTest() {
        // TODO: test precipitationAmountMax
    }

    /**
     * Test the property 'precipitationAmountMin'
     */
    @Test
    public void precipitationAmountMinTest() {
        // TODO: test precipitationAmountMin
    }

    /**
     * Test the property 'probabilityOfPrecipitation'
     */
    @Test
    public void probabilityOfPrecipitationTest() {
        // TODO: test probabilityOfPrecipitation
    }

    /**
     * Test the property 'probabilityOfThunder'
     */
    @Test
    public void probabilityOfThunderTest() {
        // TODO: test probabilityOfThunder
    }

    /**
     * Test the property 'relativeHumidity'
     */
    @Test
    public void relativeHumidityTest() {
        // TODO: test relativeHumidity
    }

    /**
     * Test the property 'ultravioletIndexClearSkyMax'
     */
    @Test
    public void ultravioletIndexClearSkyMaxTest() {
        // TODO: test ultravioletIndexClearSkyMax
    }

    /**
     * Test the property 'windFromDirection'
     */
    @Test
    public void windFromDirectionTest() {
        // TODO: test windFromDirection
    }

    /**
     * Test the property 'windSpeed'
     */
    @Test
    public void windSpeedTest() {
        // TODO: test windSpeed
    }

    /**
     * Test the property 'windSpeedOfGust'
     */
    @Test
    public void windSpeedOfGustTest() {
        // TODO: test windSpeedOfGust
    }

}
