/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spond.data.web.metno.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ForecastTimeStepDataNext6Hours
 */
public class ForecastTimeStepDataNext6HoursTest {
    private final ForecastTimeStepDataNext6Hours model = new ForecastTimeStepDataNext6Hours();

    /**
     * Model tests for ForecastTimeStepDataNext6Hours
     */
    @Test
    public void testForecastTimeStepDataNext6Hours() {
        // TODO: test ForecastTimeStepDataNext6Hours
    }

    /**
     * Test the property 'details'
     */
    @Test
    public void detailsTest() {
        // TODO: test details
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

}
