/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spond.data.web.metno.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ForecastTimeStepData
 */
public class ForecastTimeStepDataTest {
    private final ForecastTimeStepData model = new ForecastTimeStepData();

    /**
     * Model tests for ForecastTimeStepData
     */
    @Test
    public void testForecastTimeStepData() {
        // TODO: test ForecastTimeStepData
    }

    /**
     * Test the property 'instant'
     */
    @Test
    public void instantTest() {
        // TODO: test instant
    }

    /**
     * Test the property 'next12Hours'
     */
    @Test
    public void next12HoursTest() {
        // TODO: test next12Hours
    }

    /**
     * Test the property 'next1Hours'
     */
    @Test
    public void next1HoursTest() {
        // TODO: test next1Hours
    }

    /**
     * Test the property 'next6Hours'
     */
    @Test
    public void next6HoursTest() {
        // TODO: test next6Hours
    }

}
