/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spond.data.web.metno.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.spond.data.web.metno.model.WeatherSymbol;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ForecastSummary
 */
public class ForecastSummaryTest {
    private final ForecastSummary model = new ForecastSummary();

    /**
     * Model tests for ForecastSummary
     */
    @Test
    public void testForecastSummary() {
        // TODO: test ForecastSummary
    }

    /**
     * Test the property 'symbolCode'
     */
    @Test
    public void symbolCodeTest() {
        // TODO: test symbolCode
    }

}
