/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spond.data.web.metno.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for METJSONForecast
 */
public class METJSONForecastTest {
    private final METJSONForecast model = new METJSONForecast();

    /**
     * Model tests for METJSONForecast
     */
    @Test
    public void testMETJSONForecast() {
        // TODO: test METJSONForecast
    }

    /**
     * Test the property 'geometry'
     */
    @Test
    public void geometryTest() {
        // TODO: test geometry
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
