/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spond.data.web.metno.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.processing.Generated;

/**
 * Parameters with validity times over twelve hours. Will not exist for all time steps.
 */
@ApiModel(description = "Parameters with validity times over twelve hours. Will not exist for all time steps.")
@JsonPropertyOrder({
  ForecastTimeStepDataNext12Hours.JSON_PROPERTY_DETAILS,
  ForecastTimeStepDataNext12Hours.JSON_PROPERTY_SUMMARY
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-09T15:59:38.720538+02:00[Europe/Oslo]")
public class ForecastTimeStepDataNext12Hours {
  public static final String JSON_PROPERTY_DETAILS = "details";
  private ForecastTimePeriod details;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  private ForecastSummary summary;


  public ForecastTimeStepDataNext12Hours details(ForecastTimePeriod details) {
    
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ForecastTimePeriod getDetails() {
    return details;
  }


  public void setDetails(ForecastTimePeriod details) {
    this.details = details;
  }


  public ForecastTimeStepDataNext12Hours summary(ForecastSummary summary) {
    
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ForecastSummary getSummary() {
    return summary;
  }


  public void setSummary(ForecastSummary summary) {
    this.summary = summary;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastTimeStepDataNext12Hours forecastTimeStepDataNext12Hours = (ForecastTimeStepDataNext12Hours) o;
    return Objects.equals(this.details, forecastTimeStepDataNext12Hours.details) &&
        Objects.equals(this.summary, forecastTimeStepDataNext12Hours.summary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(details, summary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastTimeStepDataNext12Hours {\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

