/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spond.data.web.metno.model;

import java.time.Instant;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.processing.Generated;

/**
 * ForecastTimeStep
 */
@JsonPropertyOrder({
  ForecastTimeStep.JSON_PROPERTY_DATA,
  ForecastTimeStep.JSON_PROPERTY_TIME
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-09T15:59:38.720538+02:00[Europe/Oslo]")
public class ForecastTimeStep {
  public static final String JSON_PROPERTY_DATA = "data";
  private ForecastTimeStepData data;

  public static final String JSON_PROPERTY_TIME = "time";
  private Instant time;


  public ForecastTimeStep data(ForecastTimeStepData data) {
    
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ForecastTimeStepData getData() {
    return data;
  }


  public void setData(ForecastTimeStepData data) {
    this.data = data;
  }


  public ForecastTimeStep time(Instant time) {
    
    this.time = time;
    return this;
  }

   /**
   * The time these forecast values are valid for. Timestamp in format YYYY-MM-DDThh:mm:ssZ (ISO 8601)
   * @return time
  **/
  @ApiModelProperty(example = "2019-12-03T14:00:00Z", required = true, value = "The time these forecast values are valid for. Timestamp in format YYYY-MM-DDThh:mm:ssZ (ISO 8601)")
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Instant getTime() {
    return time;
  }


  public void setTime(Instant time) {
    this.time = time;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastTimeStep forecastTimeStep = (ForecastTimeStep) o;
    return Objects.equals(this.data, forecastTimeStep.data) &&
        Objects.equals(this.time, forecastTimeStep.time);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, time);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastTimeStep {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

