/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spond.data.web.metno.model;

import java.time.Instant;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.processing.Generated;

/**
 * ForecastMeta
 */
@JsonPropertyOrder({
  ForecastMeta.JSON_PROPERTY_UNITS,
  ForecastMeta.JSON_PROPERTY_UPDATED_AT
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-09T15:59:38.720538+02:00[Europe/Oslo]")
public class ForecastMeta {
  public static final String JSON_PROPERTY_UNITS = "units";
  private ForecastUnits units;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private String updatedAt;


  public ForecastMeta units(ForecastUnits units) {
    
    this.units = units;
    return this;
  }

   /**
   * Get units
   * @return units
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_UNITS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ForecastUnits getUnits() {
    return units;
  }


  public void setUnits(ForecastUnits units) {
    this.units = units;
  }


  public ForecastMeta updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Update time for this forecast
   * @return updatedAt
   **/
  @ApiModelProperty(example = "2019-12-03T13:52:13Z", required = true, value = "Update time for this forecast")
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastMeta forecastMeta = (ForecastMeta) o;
    return Objects.equals(this.units, forecastMeta.units) &&
        Objects.equals(this.updatedAt, forecastMeta.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(units, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastMeta {\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

