/*
 * Locationforecast
 * Weather forecast for a specified place
 *
 * The version of the OpenAPI document: 2.0
 * Contact: weatherapi-adm@met.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.spond.data.web.metno.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.processing.Generated;

/**
 * Forecast for a specific time
 */
@ApiModel(description = "Forecast for a specific time")
@JsonPropertyOrder({
  ForecastTimeStepData.JSON_PROPERTY_INSTANT,
  ForecastTimeStepData.JSON_PROPERTY_NEXT12_HOURS,
  ForecastTimeStepData.JSON_PROPERTY_NEXT1_HOURS,
  ForecastTimeStepData.JSON_PROPERTY_NEXT6_HOURS
})
@Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-09T15:59:38.720538+02:00[Europe/Oslo]")
public class ForecastTimeStepData {
  public static final String JSON_PROPERTY_INSTANT = "instant";
  private ForecastTimeStepDataInstant instant;

  public static final String JSON_PROPERTY_NEXT12_HOURS = "next_12_hours";
  private ForecastTimeStepDataNext12Hours next12Hours;

  public static final String JSON_PROPERTY_NEXT1_HOURS = "next_1_hours";
  private ForecastTimeStepDataNext1Hours next1Hours;

  public static final String JSON_PROPERTY_NEXT6_HOURS = "next_6_hours";
  private ForecastTimeStepDataNext6Hours next6Hours;


  public ForecastTimeStepData instant(ForecastTimeStepDataInstant instant) {
    
    this.instant = instant;
    return this;
  }

   /**
   * Get instant
   * @return instant
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_INSTANT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ForecastTimeStepDataInstant getInstant() {
    return instant;
  }


  public void setInstant(ForecastTimeStepDataInstant instant) {
    this.instant = instant;
  }


  public ForecastTimeStepData next12Hours(ForecastTimeStepDataNext12Hours next12Hours) {
    
    this.next12Hours = next12Hours;
    return this;
  }

   /**
   * Get next12Hours
   * @return next12Hours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NEXT12_HOURS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ForecastTimeStepDataNext12Hours getNext12Hours() {
    return next12Hours;
  }


  public void setNext12Hours(ForecastTimeStepDataNext12Hours next12Hours) {
    this.next12Hours = next12Hours;
  }


  public ForecastTimeStepData next1Hours(ForecastTimeStepDataNext1Hours next1Hours) {
    
    this.next1Hours = next1Hours;
    return this;
  }

   /**
   * Get next1Hours
   * @return next1Hours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NEXT1_HOURS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ForecastTimeStepDataNext1Hours getNext1Hours() {
    return next1Hours;
  }


  public void setNext1Hours(ForecastTimeStepDataNext1Hours next1Hours) {
    this.next1Hours = next1Hours;
  }


  public ForecastTimeStepData next6Hours(ForecastTimeStepDataNext6Hours next6Hours) {
    
    this.next6Hours = next6Hours;
    return this;
  }

   /**
   * Get next6Hours
   * @return next6Hours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NEXT6_HOURS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ForecastTimeStepDataNext6Hours getNext6Hours() {
    return next6Hours;
  }


  public void setNext6Hours(ForecastTimeStepDataNext6Hours next6Hours) {
    this.next6Hours = next6Hours;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ForecastTimeStepData forecastTimeStepData = (ForecastTimeStepData) o;
    return Objects.equals(this.instant, forecastTimeStepData.instant) &&
        Objects.equals(this.next12Hours, forecastTimeStepData.next12Hours) &&
        Objects.equals(this.next1Hours, forecastTimeStepData.next1Hours) &&
        Objects.equals(this.next6Hours, forecastTimeStepData.next6Hours);
  }

  @Override
  public int hashCode() {
    return Objects.hash(instant, next12Hours, next1Hours, next6Hours);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ForecastTimeStepData {\n");
    sb.append("    instant: ").append(toIndentedString(instant)).append("\n");
    sb.append("    next12Hours: ").append(toIndentedString(next12Hours)).append("\n");
    sb.append("    next1Hours: ").append(toIndentedString(next1Hours)).append("\n");
    sb.append("    next6Hours: ").append(toIndentedString(next6Hours)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

